# Generated by Django 4.2.4 on 2023-08-18 06:46

import core.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WhitePapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('detail', models.TextField(default='')),
                ('about', models.TextField(default='')),
                ('status', models.CharField(choices=[('Arcives', 'Arcives'), ('Published', 'Published'), ('Draft', 'Draft')], default='draft', max_length=120)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique_for_date='published_at')),
                ('count_of_downloads', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='whitepapers/files/', validators=[django.core.validators.FileExtensionValidator(['pdf']), core.utils.validate_file])),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whitepapers.topic')),
            ],
        ),
    ]
