# Generated by Django 4.2.4 on 2023-08-15 04:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WhitePapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('arcives', 'Arcives'), ('published', 'published'), ('draft', 'draft')], default='draft', max_length=120)),
                ('publication', models.DateField(default=django.utils.timezone.now)),
                ('download', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='whitepapers/')),
                ('file', models.FileField(upload_to='whitepapers/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whitepapers.topic')),
            ],
        ),
    ]
