# Generated by Django 4.2.4 on 2023-08-22 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('whitepapers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdownload')),
                ('whitepaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whitepapers.whitepapers')),
            ],
        ),
    ]
