# Generated by Django 4.2.4 on 2023-08-18 06:48

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitepapers',
            name='image',
            field=models.ImageField(blank=True, upload_to='whitepapers/images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), core.utils.validate_file]),
        ),
    ]
