# Generated by Django 4.2.4 on 2023-08-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitepapers',
            name='about',
            field=models.TextField(default='lorem ipsmi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitepapers',
            name='detail',
            field=models.TextField(default='lorem ipsum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whitepapers',
            name='status',
            field=models.CharField(choices=[('arcives', 'Arcives'), ('published', 'Published'), ('draft', 'draft')], default='draft', max_length=120),
        ),
    ]
