# Generated by Django 4.2.4 on 2023-08-18 06:52

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepapers', '0002_whitepapers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitepapers',
            name='file',
        ),
        migrations.AddField(
            model_name='whitepapers',
            name='pdf',
            field=models.FileField(blank=True, upload_to='whitepapers/pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf']), core.utils.validate_file]),
        ),
    ]
