# Generated by Django 4.2.4 on 2023-08-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepapers', '0002_whitepapers_about_whitepapers_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitepapers',
            old_name='download',
            new_name='count_of_downloads',
        ),
        migrations.RenameField(
            model_name='whitepapers',
            old_name='publication',
            new_name='published_at',
        ),
        migrations.AlterField(
            model_name='whitepapers',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='whitepapers',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='whitepapers',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
