# Generated by Django 4.2.4 on 2023-08-20 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_country'),
        ('whitepapers', '0003_remove_whitepapers_file_whitepapers_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitePapersDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('whitepaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whitepapers.whitepapers')),
            ],
        ),
    ]
