# Generated by Django 4.2.4 on 2023-08-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepapers', '0003_rename_download_whitepapers_count_of_downloads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitepapers',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique_for_date='published_at'),
        ),
    ]
