# Generated by Django 4.2.4 on 2023-08-15 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepapers', '0004_whitepapers_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitepapers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 15, 13, 39, 2, 111224, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitepapers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='whitepapers',
            name='file',
            field=models.FileField(upload_to='whitepapers/files/'),
        ),
        migrations.AlterField(
            model_name='whitepapers',
            name='image',
            field=models.ImageField(upload_to='whitepapers/images/'),
        ),
        migrations.AlterField(
            model_name='whitepapers',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whitepapers',
            name='status',
            field=models.CharField(choices=[('Arcives', 'Arcives'), ('Published', 'Published'), ('Draft', 'Draft')], default='draft', max_length=120),
        ),
    ]
