# Generated by Django 4.2.4 on 2023-08-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepapers', '0005_whitepapers_created_at_whitepapers_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitepapers',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
